sudo: required
services:
  - docker

before_install:
   - docker build -t enricjorda/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true enricjorda/react-test npm test

after_success:
  - docker build -t enricjorda/multi-client ./client
  - docker build -t enricjorda/multi-nginx ./nginx
  - docker build -t enricjorda/multi-server ./server
  - docker build -t enricjorda/multi-worker ./worker
  # Log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take this images and push them to docker hub
  - docker push enricjorda/multi-client
  - docker push enricjorda/multi-nginx
  - docker push enricjorda/multi-server
  - docker push enricjorda/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-521068133029
  bucket_path: docker-multi
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
    

